#############################################################################
# Makefile for building: EditableItems
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  EditableItems.pro
# Template: app
# Command: /opt/Qt5.6.1/5.6/gcc_64/bin/qmake -spec linux-g++ -o Makefile EditableItems.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt5.6.1/5.6/gcc_64/include -I/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets -I/opt/Qt5.6.1/5.6/gcc_64/include/QtGui -I/opt/Qt5.6.1/5.6/gcc_64/include/QtCore -I. -I. -I/opt/Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt5.6.1/5.6/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = EditableItems1.0.0
DISTDIR = /media/fady/Data/Work/Projects/Programming/Breeze_Collection/EditableItems/.tmp/EditableItems1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt5.6.1/5.6/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/Qt5.6.1/5.6/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		baseitem.cpp \
		editorscene.cpp \
		basicshapeitem.cpp \
		handle.cpp \
		complexshapeitem.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_editorscene.cpp
OBJECTS       = main.o \
		mainwindow.o \
		baseitem.o \
		editorscene.o \
		basicshapeitem.o \
		handle.o \
		complexshapeitem.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_editorscene.o
DIST          = /opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/lex.prf \
		EditableItems.pro mainwindow.h \
		baseitem.h \
		editorscene.h \
		basicshapeitem.h \
		handle.h \
		complexshapeitem.h main.cpp \
		mainwindow.cpp \
		baseitem.cpp \
		editorscene.cpp \
		basicshapeitem.cpp \
		handle.cpp \
		complexshapeitem.cpp
QMAKE_TARGET  = EditableItems
DESTDIR       = 
TARGET        = EditableItems


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EditableItems.pro /opt/Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/lex.prf \
		EditableItems.pro \
		resources.qrc \
		/opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Widgets.prl \
		/opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile EditableItems.pro
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/uic.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/file_copies.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.6.1/5.6/gcc_64/mkspecs/features/lex.prf:
EditableItems.pro:
resources.qrc:
/opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Widgets.prl:
/opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile EditableItems.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h baseitem.h editorscene.h basicshapeitem.h handle.h complexshapeitem.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp baseitem.cpp editorscene.cpp basicshapeitem.cpp handle.cpp complexshapeitem.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		Resources/character_design.jpg
	/opt/Qt5.6.1/5.6/gcc_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_editorscene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_editorscene.cpp
moc_mainwindow.cpp: /opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qicon.h \
		mainwindow.h
	/opt/Qt5.6.1/5.6/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++ -I/media/fady/Data/Work/Projects/Programming/Breeze_Collection/EditableItems -I/opt/Qt5.6.1/5.6/gcc_64/include -I/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets -I/opt/Qt5.6.1/5.6/gcc_64/include/QtGui -I/opt/Qt5.6.1/5.6/gcc_64/include/QtCore mainwindow.h -o moc_mainwindow.cpp

moc_editorscene.cpp: /opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsScene \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsscene.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/QKeyEvent \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtouchdevice.h \
		editorscene.h
	/opt/Qt5.6.1/5.6/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++ -I/media/fady/Data/Work/Projects/Programming/Breeze_Collection/EditableItems -I/opt/Qt5.6.1/5.6/gcc_64/include -I/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets -I/opt/Qt5.6.1/5.6/gcc_64/include/QtGui -I/opt/Qt5.6.1/5.6/gcc_64/include/QtCore editorscene.h -o moc_editorscene.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/Qt5.6.1/5.6/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QSettings \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qicon.h \
		ui_mainwindow.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QVariant \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QAction \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qaction.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QButtonGroup \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QCheckBox \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qcheckbox.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsView \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsview.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qscrollarea.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsscene.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QHeaderView \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qheaderview.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qvalidator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregularexpression.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qslider.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qstyle.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qtabbar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qrubberband.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QMenuBar \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qmenubar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qmenu.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QPushButton \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QRadioButton \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qradiobutton.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QStatusBar \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qstatusbar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QToolBar \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qtoolbar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QVBoxLayout \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qboxlayout.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qlayout.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qlayoutitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgridlayout.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsRectItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsitem.h \
		editorscene.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsScene \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/QKeyEvent \
		basicshapeitem.h \
		baseitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsEllipseItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QList \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsSceneMouseEvent \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicssceneevent.h \
		handle.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QRectF \
		complexshapeitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QStyleFactory \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qstylefactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

baseitem.o: baseitem.cpp baseitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsEllipseItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QList \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsSceneMouseEvent \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicssceneevent.h \
		handle.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QRectF \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QUuid \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/quuid.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QSettings \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsettings.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsScene \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsscene.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baseitem.o baseitem.cpp

editorscene.o: editorscene.cpp editorscene.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsScene \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsscene.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/QKeyEvent \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorscene.o editorscene.cpp

basicshapeitem.o: basicshapeitem.cpp basicshapeitem.h \
		baseitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsEllipseItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QList \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsSceneMouseEvent \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicssceneevent.h \
		handle.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QRectF \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsScene \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basicshapeitem.o basicshapeitem.cpp

handle.o: handle.cpp handle.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QRectF \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handle.o handle.cpp

complexshapeitem.o: complexshapeitem.cpp complexshapeitem.h \
		baseitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicsitem.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsEllipseItem \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QList \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/QGraphicsSceneMouseEvent \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtWidgets/qgraphicssceneevent.h \
		handle.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QRectF \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QSettings \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qsettings.h \
		/opt/Qt5.6.1/5.6/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o complexshapeitem.o complexshapeitem.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_editorscene.o: moc_editorscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorscene.o moc_editorscene.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

